### ISSUE TITLE
Huge number of broken data links on data.gov.uk

### ISSUE THREAD

**Issue by rufuspollock** [openknowledge-archive/issues-archived#1]
For data and analysis see http://explorer.okfnlabs.org/#rgrp/925a0022741082515ee8/view/grid

To summarize:

Extracted on 2013-08-16 from this source: http://data.gov.uk/api/2/util/qa/organisations_with_broken_resource_links/report.csv?include_sub_publishers=1

Total number of broken items:
- Datasets (broken package count): 4112 (42% of all datasets)
- Data files (Resources): 15328

Not totally sure what broken package count but my guess is that it is datasets with at least one broken resource.
## Comments
- these are pretty big numbers
- this is _not_ data.gov.uk's fault - they have to link out to other stuff and do not have any real ability to control or sanction other departments that break links
- My guess is that changes of UK gov websites onto gov.uk has massively increased link breakages (unfortunately I don't have stats from before start of changeover) - see e.g. https://twitter.com/rufuspollock/status/368433406532546560  (that broken link came from http://data.gov.uk/dataset/local_authority_carbon_dioxide_emissions)

**Comment by rossjones** [comment]
Worth checking it doesn't include those reporting the wrong format as well. I can do that later.

**Comment by rufuspollock** [comment]
@rossjones that would be nice. I'd also really like a nice way to get resource count / dataset counts per organization so I could do percentages and make a nice leaderboard ;-) (better than crude one current live at http://explorer.okfnlabs.org/#rgrp/925a0022741082515ee8/view/graph which isn't normalized (dept of health may not be worst in percentage terms ...)

/cc @dread

**Comment by rossjones** [comment]
It isn't just 404s, it is also 410s (as bad I guess) and connection errors where we are connecting to a https URL and the certificate no longer matches after the redirect. But I guess broken links are broken links.

**Comment by rossjones** [comment]
Would definitely be nice to have the resource/dataset counts per org in the QA API.  I'll add a ticket but Aug is a very bad month atm so workarounds ahoy I think.

I started working on a script using the weekly data dumps, but it doesn't contain the publisher hierarchy so it wouldn't show the child counts included with each publisher. It would however show exactly which publisher (not just the top level ones) had the broken links... still useful? You'd need to make sure the API call included include_sub_publishers=0 but would then be hard to see which top-level depts weren't doing so well.

https://classic.scraperwiki.com/scrapers/dgu_resource_counts/

I'll have a think, maybe I could just run a script against the live db as a one-off?

**Comment by davidread** [comment]
We've had a push on this with publishers and we're down to 6% of resources being broken.

http://data.gov.uk/data/report/broken-links?include_sub_organizations=1

**Comment by rufuspollock** [comment]
@davidread this is amazing. Shall we close this ticket then?

**Comment by davidread** [comment]
That would be great
